/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package siecipetriego;

import java.awt.Dimension;
import java.awt.Point;
import java.util.HashMap;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author Mateusz
 */
public class EditPassagePanel extends JDialog {

    private HashMap<String, String> returnValues;
    /**
     * Creates new form EditPassagePanel
     */
    public EditPassagePanel(JFrame parent, String title, boolean modal, HashMap<String, String> values) {
        super(parent, title, modal);
        initComponents();
        if(parent != null){
            Dimension parentSize = parent.getSize();
            Point parentLocation = parent.getLocation();
            setLocation(parentLocation.x + parentSize.width / 4, parentLocation.y + parentSize.height / 4);
        }
        returnValues = values;
        setPreferredSize(new Dimension(370,255));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pack();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        titleLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        tokenCountLabel = new javax.swing.JLabel();
        capacityLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        capacityTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        tocenCountTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLabel.setText("Przepustowość:");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 25));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, 259, 10));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLabel.setText("Edycja przejścia:");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 122, -1));

        cancelButton.setBackground(new java.awt.Color(204, 51, 0));
        cancelButton.setText("Anuluj");
        add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 148, 96, 34));

        tokenCountLabel.setText("Priorytet:");
        add(tokenCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, 130, 25));

        capacityLabel.setText("Czas:");
        add(capacityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, 130, 25));

        nameTextField.setText("jTextField1");
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 50, 200, 25));

        capacityTextField.setText("jTextField1");
        add(capacityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 112, 200, 25));

        submitButton.setBackground(new java.awt.Color(51, 204, 0));
        submitButton.setText("Zatwierdź");
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 148, 96, 34));

        tocenCountTextField.setText("jTextField1");
        add(tocenCountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 81, 200, 25));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel capacityLabel;
    private javax.swing.JTextField capacityTextField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField tocenCountTextField;
    private javax.swing.JLabel tokenCountLabel;
    // End of variables declaration//GEN-END:variables
}
