/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package siecipetriego;

import java.awt.Dimension;
import java.awt.Point;
import java.util.HashMap;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JTabbedPane;
import siecipetriego.model.Miejsce;

/**
 *
 * @author Mateusz
 */
public class EditPlacePanel extends JDialog {

    private HashMap<String, Object> returnValues;
    /**
     * Creates new form EditPlacePanel
     */
    public EditPlacePanel(JFrame parent, String title, boolean modal, HashMap<String, Object> values) {
        
        super(parent, title, modal);                                                                        // inicjalizacja okna dialogowego
        initComponents();
        if(parent != null){
            Dimension parentSize = parent.getSize();
            Point parentLocation = parent.getLocation();
            setLocation(parentLocation.x + parentSize.width / 4, parentLocation.y + parentSize.height / 4);
        }
        returnValues = values;
        
        Miejsce vertex = (Miejsce)values.get("Object");                                                     // pobranie danych modyfikowanego miejsca
        tocenCountTextField.setText(new Integer(vertex.getTokenCount()).toString());                        // wypełnienie pól formularza:
        nameTextField.setText(vertex.getName());
        typeTextField.setText(vertex.getType());
        capacityTextField.setText(new Integer(vertex.getCapacity()).toString());
        
        setPreferredSize(new Dimension(370,255));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pack();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        tokenCountLabel = new javax.swing.JLabel();
        capacityLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        tocenCountTextField = new javax.swing.JTextField();
        capacityTextField = new javax.swing.JTextField();
        typeTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setModal(true);
        setPreferredSize(new java.awt.Dimension(350, 225));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLabel.setText("Edycja miejsca:");
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 122, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, 259, 10));

        nameLabel.setText("Nazwa:");
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 25));

        nameTextField.setText("jTextField1");
        getContentPane().add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 50, 200, 25));

        tokenCountLabel.setText("Liczba tokenów:");
        getContentPane().add(tokenCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, 130, 25));

        capacityLabel.setText("Pojemność:");
        getContentPane().add(capacityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, 130, 25));

        typeLabel.setText("Typ:");
        getContentPane().add(typeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 143, 130, 25));

        tocenCountTextField.setText("jTextField1");
        getContentPane().add(tocenCountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 81, 200, 25));

        capacityTextField.setText("jTextField1");
        getContentPane().add(capacityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 112, 200, 25));

        typeTextField.setText("jTextField1");
        getContentPane().add(typeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 143, 200, 25));

        submitButton.setBackground(new java.awt.Color(51, 204, 0));
        submitButton.setText("Zatwierdź");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 179, 96, 34));

        cancelButton.setBackground(new java.awt.Color(204, 51, 0));
        cancelButton.setText("Anuluj");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 179, 96, 34));
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

        returnValues.put("Status", "Ok");                                               // aktualizacja statusu 
        Miejsce miejsce = new Miejsce((Miejsce)returnValues.get("Object"));             // stworzenie nowego miejsca
        
        miejsce.setName(nameTextField.getText());                                       // pobranie danych z pól formularza i zapisanie do nowego obiektu
        miejsce.setTokenCount(Integer.parseInt(tocenCountTextField.getText()));
        miejsce.setCapacity(Integer.parseInt(capacityTextField.getText()));
        miejsce.setType(typeTextField.getText());
        returnValues.put("ReturnObject", miejsce);                                      // zapisanie nowego obiektu do wartości zwracanych
        setVisible(false);                                                              // usunięcie okna dialogowego
        dispose();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed

        returnValues.put("Status", "Cancel");                                           // aktualizacja statusu 
        setVisible(false);                                                              // usunięcie okna dialogowego
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel capacityLabel;
    private javax.swing.JTextField capacityTextField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField tocenCountTextField;
    private javax.swing.JLabel tokenCountLabel;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JTextField typeTextField;
    // End of variables declaration//GEN-END:variables
}
