package com.petri.nets.gui;

import java.awt.Dimension;
import java.awt.Point;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.JFrame;

import com.petri.nets.model.Transition;
import javax.swing.JOptionPane;

public class EditTransitionPanel extends JDialog {

    private static final String ERROR_MESSAGE_TITLE = "BŁĄD";
    private Map<String, Object> returnValues;

    /**
     * Creates new form EditPassagePanel
     */
    public EditTransitionPanel(JFrame parent, String title, boolean modal, Map<String, Object> values) {
        super(parent, title, modal);                                                                            // inicjalizacja okna dialogowego
        initComponents();
        if (parent != null) {
            Dimension parentSize = parent.getSize();
            Point parentLocation = parent.getLocation();
            setLocation(parentLocation.x + parentSize.width / 4, parentLocation.y + parentSize.height / 4);
        }
        returnValues = values;
        Transition vertex = (Transition) values.get("Object");                                                     // pobranie dantych modyfikowanego przejścia
        nameTextField.setText(vertex.getName());                                                                // wypełnienie pól formularza:
        priorityTextField.setText(Integer.toString(vertex.getPriority()));
        if (!vertex.isPriority()) { // nie wyświetlanie informacji o priorytecie w przypadku sieci ogólnych
            priorityLabel.setVisible(false);
            priorityTextField.setVisible(false);
        }
        setPreferredSize(new Dimension(370, 255));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pack();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        titleLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        priorityLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        priorityTextField = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLabel.setText("Nazwa:");
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 25));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, 259, 10));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLabel.setText("Edycja przejścia:");
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 122, -1));

        cancelButton.setBackground(new java.awt.Color(204, 51, 0));
        cancelButton.setText("Anuluj");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 96, 34));

        priorityLabel.setText("Priorytet:");
        getContentPane().add(priorityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, 130, 25));
        getContentPane().add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 50, 200, 25));

        submitButton.setBackground(new java.awt.Color(51, 204, 0));
        submitButton.setText("Zatwierdź");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 96, 34));
        getContentPane().add(priorityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 81, 200, 25));
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        returnValues.put("Status", "Cancel");                                           // aktualizacja statusu w zwracanych wartościach
        setVisible(false);                                                              // usunięcie okna dialogowego
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        
        // aktualizacja statusu 
        returnValues.remove("Status");  
        // akatualizacja statusu w zwracanych wartościach
        Transition transition = new Transition((Transition) returnValues.get("Object"));     // tworzenie nowego przejścia
        
        // bufor na komunikaty błędów.
        StringBuilder errorMessage = new StringBuilder();
        
        try {
            
            // Sprawdzanie nazwy
            String name = nameTextField.getText();
            if (name.isEmpty()) {
                errorMessage.append("Nazwa miejsca nie może być pusta.\n");
                returnValues.put("Status", "Errors"); 
            } else {
                transition.setName(name);  
            }
            
            // Sprawdzanie priorytetu
            int priority = Integer.parseInt(priorityTextField.getText());
            if (priority < 0) {
                errorMessage.append("Priorytet nie może być ujemny.\n");
                returnValues.put("Status", "Errors");  
            } else {
                transition.setPriority(priority);
            }

                           
        } catch(NumberFormatException e) {
            errorMessage.append("Priorytet musi być liczbą.\n");
            returnValues.put("Status", "Errors"); 
        }
 
        // zapisanie nowego obiektu do wartości zwracanych
        returnValues.put("ReturnObject", transition);   
      
        if (returnValues.get("Status") == null || !returnValues.get("Status").equals("Errors")) {
            returnValues.put("Status", "Ok");
            setVisible(false);  // usunięcie okna dialogowego     
            dispose();
        } else if (returnValues.get("Status").equals("Errors")) {     
            JOptionPane.showMessageDialog(this, errorMessage.toString(), ERROR_MESSAGE_TITLE, JOptionPane.ERROR_MESSAGE);
        }      
    }//GEN-LAST:event_submitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField priorityTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel priorityLabel;
    // End of variables declaration//GEN-END:variables
}
