package com.petri.nets.gui;

import java.awt.Dimension;
import java.awt.Point;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.JFrame;

import com.petri.nets.model.Transition;

/**
 *
 * @author Mateusz
 */
public class EditTransitionPanel extends JDialog {

    private Map<String, Object> returnValues;

    /**
     * Creates new form EditPassagePanel
     */
    public EditTransitionPanel(JFrame parent, String title, boolean modal, Map<String, Object> values) {

        super(parent, title, modal);                                                                            // inicjalizacja okna dialogowego
        initComponents();
        if (parent != null) {
            Dimension parentSize = parent.getSize();
            Point parentLocation = parent.getLocation();
            setLocation(parentLocation.x + parentSize.width / 4, parentLocation.y + parentSize.height / 4);
        }
        returnValues = values;

        Transition vertex = (Transition) values.get("Object");                                                     // pobranie dantych modyfikowanego przejścia
        nameTextField.setText(vertex.getName());                                                                // wypełnienie pól formularza:
        priorityTextField.setText(Integer.toString(vertex.getPriority()));

        setPreferredSize(new Dimension(370, 255));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pack();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        titleLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        tokenCountLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        priorityTextField = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLabel.setText("Przepustowość:");
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 25));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, 259, 10));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLabel.setText("Edycja przejścia:");
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 122, -1));

        cancelButton.setBackground(new java.awt.Color(204, 51, 0));
        cancelButton.setText("Anuluj");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 96, 34));

        tokenCountLabel.setText("Priorytet:");
        getContentPane().add(tokenCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, 130, 25));
        getContentPane().add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 50, 200, 25));

        submitButton.setBackground(new java.awt.Color(51, 204, 0));
        submitButton.setText("Zatwierdź");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 96, 34));
        getContentPane().add(priorityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 81, 200, 25));
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed

        returnValues.put("Status", "Cancel");                                           // aktualizacja statusu w zwracanych wartościach
        setVisible(false);                                                              // usunięcie okna dialogowego
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

        returnValues.put("Status", "Ok");                                               // akatualizacja statusu w zwracanych wartościach
        Transition transition = new Transition((Transition) returnValues.get("Object"));     // tworzenie nowego przejścia

        transition.setName(nameTextField.getText());                                     // pobranie danych z pól i zapisanie do nowego przejścia
        transition.setPriority(Integer.parseInt(priorityTextField.getText()));
        returnValues.put("ReturnObject", transition);                                    // dodanie nowego przejścia do wartości zwracanych
        setVisible(false);                                                              // usunięcie okna dialogowego
        dispose();
    }//GEN-LAST:event_submitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField priorityTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel tokenCountLabel;
    // End of variables declaration//GEN-END:variables
}
