package com.petri.nets.gui;

import java.awt.Dimension;
import java.awt.Point;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.JFrame;

import com.petri.nets.model.Edge;
import javax.swing.JOptionPane;

public class EditEdgePanel extends JDialog {

    private static final String ERROR_MESSAGE_TITLE = "BŁĄD";
    private Map<String, Object> returnValues;

    /**
     * Creates new form EditEdgePanel
     */
    public EditEdgePanel(JFrame parent, String title, boolean modal, Map<String, Object> values) {
        super(parent, title, modal);                                                                                // inicjalizacja okna dialogowego
        initComponents();
        if (parent != null) {
            Dimension parentSize = parent.getSize();
            Point parentLocation = parent.getLocation();
            setLocation(parentLocation.x + parentSize.width / 4, parentLocation.y + parentSize.height / 4);
        }
        returnValues = values;
        Edge edge = (Edge) returnValues.get("Object");                                                               // pobranie danych modyfikowanej krawędzi
        capacityTextField.setText(Integer.toString(edge.getCapacity()));                                            // wypełnienie pól formularza
        setPreferredSize(new Dimension(370, 200));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pack();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conditionLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        capacityTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        conditionLabel.setText("Pojemność:");
        getContentPane().add(conditionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 25));

        cancelButton.setBackground(new java.awt.Color(204, 51, 0));
        cancelButton.setText("Anuluj");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 96, 34));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLabel.setText("Edycja krawędzi:");
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 122, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, 259, 10));
        getContentPane().add(capacityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 200, 25));

        submitButton.setBackground(new java.awt.Color(51, 204, 0));
        submitButton.setText("Zatwierdź");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 96, 34));
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        
        // stworzenie nowej krawędzi
        Edge edge = new Edge((Edge) returnValues.get("Object"));        
        
        // aktualizacja statusu 
        returnValues.remove("Status");
        
        // bufor na komunikaty błędów
        StringBuilder errorMessage = new StringBuilder();
        
        try {
            
            // Sprawdzanie pojemności
            int capacity = Integer.parseInt(capacityTextField.getText());
            if (capacity < 0) {
                errorMessage.append("Pojemność nie może być ujemna.\n");
                returnValues.put("Status", "Errors");  
            } else {
                edge.setCapacity(capacity);
            }
                                   
        } catch(NumberFormatException e) {
            errorMessage.append("Pojemność musi być liczbą.\n");
            returnValues.put("Status", "Errors"); 
        }
 
        // zapisanie nowego obiektu do wartości zwracanych
        returnValues.put("ReturnObject", edge);  
            
        if (returnValues.get("Status") == null || !returnValues.get("Status").equals("Errors")) {
            returnValues.put("Status", "Ok");
            setVisible(false);  // usunięcie okna dialogowego     
            dispose();
        } else if (returnValues.get("Status").equals("Errors")) {     
            JOptionPane.showMessageDialog(this, errorMessage.toString(), ERROR_MESSAGE_TITLE, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        returnValues.put("Status", "Cancel");                                               // aktualizacja statusu
        setVisible(false);                                                                  // usunięcie okna dialogowego
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField capacityTextField;
    private javax.swing.JLabel conditionLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
