/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.petri.nets.gui;

import java.awt.Dimension;
import java.awt.Label;
import java.util.HashMap;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author LordMajer
 */
public class GeneralRaportDialog extends JDialog {

    private HashMap<String, Object> properties;
    /**
     * Creates new form GeneralRaportDialog
     */
    public GeneralRaportDialog(java.awt.Frame parent, boolean modal, HashMap<String, Object> properties) {
        super(parent,"Raport", modal);
        initComponents();
        
        this.properties = properties;
        initResults();
        setPreferredSize(new Dimension(640, 480));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pack();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        generalPanel = new javax.swing.JPanel();
        propertiesPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        safenessText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        boundednessText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        reversibilityText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        conservatismText = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        netLivenessText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        propertiesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Właściwości"));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Bezpieczeństwo:");

        safenessText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        safenessText.setText("TAK");
        safenessText.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("K-Ograniczoność:");

        boundednessText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boundednessText.setText("1-ograniczona");
        boundednessText.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Odwracalność:");

        reversibilityText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        reversibilityText.setText("TAK");
        reversibilityText.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Zachowawczość:");

        conservatismText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        conservatismText.setText("TAK");
        conservatismText.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Zywotność sieci:");

        netLivenessText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        netLivenessText.setText("TAK");
        netLivenessText.setEnabled(false);

        javax.swing.GroupLayout propertiesPanelLayout = new javax.swing.GroupLayout(propertiesPanel);
        propertiesPanel.setLayout(propertiesPanelLayout);
        propertiesPanelLayout.setHorizontalGroup(
            propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(safenessText)
                    .addComponent(boundednessText, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(reversibilityText)
                    .addComponent(conservatismText)
                    .addComponent(netLivenessText))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        propertiesPanelLayout.setVerticalGroup(
            propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertiesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(safenessText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(boundednessText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(reversibilityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(conservatismText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(netLivenessText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout generalPanelLayout = new javax.swing.GroupLayout(generalPanel);
        generalPanel.setLayout(generalPanelLayout);
        generalPanelLayout.setHorizontalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(propertiesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        generalPanelLayout.setVerticalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addComponent(propertiesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 178, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Ogólne", generalPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void initResults(){
        
        // aktualizacja zakładki Ogólne:
        updateGeneral();
        
        // aktualizacja macierzy:
        tabbedPane.addTab("Macierz wejść", (JScrollPane)properties.get("InputMatrix"));
        tabbedPane.addTab("Macierz wyjść", (JScrollPane)properties.get("OutputMatrix"));
        tabbedPane.addTab("Macierz incydencji", (JScrollPane)properties.get("IncidenceMatrix"));
        
        // aktualizacja zakładek grafów i drzewa
        tabbedPane.addTab("Graf osiągalności", (JScrollPane)properties.get("ReachablilityGraph"));
        tabbedPane.addTab("Graf pokrycia", (JScrollPane)properties.get("CoverageGraph"));
        tabbedPane.addTab("Drzewo pokrycia", (JScrollPane)properties.get("CoverageTree"));
    }
    
    
    public void updateGeneral(){
        
        // Bezpieczeństwo:
        String safenessString = (String)properties.get("Sefeness");
        if(safenessString.equals("Sieć jest żywotna")){
            safenessText.setText("TAK");
        }else{
            safenessText.setText("NIE");
        };
        
        // Ograniczoność:
        boundednessText.setText((String)properties.get("Boundedness"));
        
        // Odwracalność:
        if(((String)properties.get("Reversibility")).equals("Sieć jest odwracalna")){
            reversibilityText.setText("TAK");
        }else{
            reversibilityText.setText("NIE");
        }
        
        // Zachowawczość:
        if(((String)properties.get("Conservatism")).equals("Sieć jest zachowawcza")){
            conservatismText.setText("TAK");
        }else{
            conservatismText.setText("NIE");
        }
        
        // Żywotność sieci:
        if(((String)properties.get("NetLiveness")).equals("Sieć jest żywotna")){
            reversibilityText.setText("TAK");
        }else{
            reversibilityText.setText("NIE");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boundednessText;
    private javax.swing.JTextField conservatismText;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JTextField netLivenessText;
    private javax.swing.JPanel propertiesPanel;
    private javax.swing.JTextField reversibilityText;
    private javax.swing.JTextField safenessText;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
