/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.petri.nets.gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Label;
import java.util.HashMap;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author LordMajer
 */
public class GeneralRaportDialog extends JDialog {

    private HashMap<String, Object> properties;
    /**
     * Creates new form GeneralRaportDialog
     */
    public GeneralRaportDialog(java.awt.Frame parent, boolean modal, HashMap<String, Object> properties) {
        super(parent,"Raport", modal);
        initComponents();
        
        this.properties = properties;
        initResults();
        setPreferredSize(new Dimension(640, 480));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pack();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        generalPanel = new javax.swing.JPanel();
        propertiesPanel = new javax.swing.JPanel();
        safenessLabel = new javax.swing.JLabel();
        boundednessLabel = new javax.swing.JLabel();
        reversibilityLabel = new javax.swing.JLabel();
        conservatismLabel = new javax.swing.JLabel();
        netLivenessLabel = new javax.swing.JLabel();
        safenessText = new javax.swing.JLabel();
        boundednessText = new javax.swing.JLabel();
        reversibilityText = new javax.swing.JLabel();
        conservatismText = new javax.swing.JLabel();
        netLivenessText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        propertiesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Właściwości"));

        safenessLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        safenessLabel.setText("Bezpieczeństwo:");

        boundednessLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boundednessLabel.setText("K-Ograniczoność:");

        reversibilityLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        reversibilityLabel.setText("Odwracalność:");

        conservatismLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        conservatismLabel.setText("Zachowawczość:");

        netLivenessLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        netLivenessLabel.setText("Zywotność sieci:");

        safenessText.setBackground(new java.awt.Color(0, 204, 0));
        safenessText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        safenessText.setText("TAK");
        safenessText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        safenessText.setOpaque(true);

        boundednessText.setBackground(new java.awt.Color(51, 204, 0));
        boundednessText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boundednessText.setText("TAK");
        boundednessText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boundednessText.setOpaque(true);

        reversibilityText.setBackground(new java.awt.Color(51, 204, 0));
        reversibilityText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        reversibilityText.setText("TAK");
        reversibilityText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reversibilityText.setOpaque(true);

        conservatismText.setBackground(new java.awt.Color(51, 204, 0));
        conservatismText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        conservatismText.setText("TAK");
        conservatismText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        conservatismText.setOpaque(true);

        netLivenessText.setBackground(new java.awt.Color(51, 204, 0));
        netLivenessText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        netLivenessText.setText("TAK");
        netLivenessText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        netLivenessText.setOpaque(true);

        javax.swing.GroupLayout propertiesPanelLayout = new javax.swing.GroupLayout(propertiesPanel);
        propertiesPanel.setLayout(propertiesPanelLayout);
        propertiesPanelLayout.setHorizontalGroup(
            propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(netLivenessLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(conservatismLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reversibilityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boundednessLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(safenessLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(safenessText, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(boundednessText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reversibilityText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(conservatismText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(netLivenessText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        propertiesPanelLayout.setVerticalGroup(
            propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertiesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(safenessLabel)
                    .addComponent(safenessText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boundednessLabel)
                    .addComponent(boundednessText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reversibilityLabel)
                    .addComponent(reversibilityText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conservatismLabel)
                    .addComponent(conservatismText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(netLivenessLabel)
                    .addComponent(netLivenessText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout generalPanelLayout = new javax.swing.GroupLayout(generalPanel);
        generalPanel.setLayout(generalPanelLayout);
        generalPanelLayout.setHorizontalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(propertiesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        generalPanelLayout.setVerticalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addComponent(propertiesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 202, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Ogólne", generalPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void initResults(){
        
        // aktualizacja zakładki Ogólne:
        updateGeneral();
        
        // aktualizacja macierzy:
        tabbedPane.addTab("Macierz wejść", (JScrollPane)properties.get("InputMatrix"));
        tabbedPane.addTab("Macierz wyjść", (JScrollPane)properties.get("OutputMatrix"));
        tabbedPane.addTab("Macierz incydencji", (JScrollPane)properties.get("IncidenceMatrix"));
        
        // aktualizacja zakładek grafów i drzewa
        tabbedPane.addTab("Graf osiągalności", (JScrollPane)properties.get("ReachablilityGraph"));
        tabbedPane.addTab("Graf pokrycia", (JScrollPane)properties.get("CoverageGraph"));
        tabbedPane.addTab("Drzewo pokrycia", (JScrollPane)properties.get("CoverageTree"));
    }
    
    
    public void updateGeneral(){
        
        // Bezpieczeństwo:
        String safenessString = (String)properties.get("Safeness");
        if(safenessString.equals("Sieć jest bezpieczna")){
            safenessText.setText("TAK");
            safenessText.setBackground(Color.green);
        }else{
            safenessText.setText("NIE");
            safenessText.setBackground(Color.red);
        };
        
        // Ograniczoność:
        boundednessText.setText((String)properties.get("Boundedness"));
        boundednessText.setBackground(Color.green);
        
        // Odwracalność:
        if(((String)properties.get("Reversibility")).equals("Sieć jest odwracalna")){
            reversibilityText.setText("TAK");
            reversibilityText.setBackground(Color.green);
        }else{
            reversibilityText.setText("NIE");
            reversibilityText.setBackground(Color.red);
        }
        
        // Zachowawczość:
        if(((String)properties.get("Conservatism")).equals("Sieć jest zachowawcza")){
            conservatismText.setText("TAK");
            conservatismText.setBackground(Color.green);
        }else{
            conservatismText.setText("NIE");
            conservatismText.setBackground(Color.red);
        }
        
        // Żywotność sieci:
        if(((String)properties.get("NetLiveness")).equals("Sieć jest żywotna")){
            netLivenessText.setText("TAK");
            netLivenessText.setBackground(Color.green);
        }else{
            netLivenessText.setText("NIE");
            netLivenessText.setBackground(Color.red);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boundednessLabel;
    private javax.swing.JLabel boundednessText;
    private javax.swing.JLabel conservatismLabel;
    private javax.swing.JLabel conservatismText;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JLabel netLivenessLabel;
    private javax.swing.JLabel netLivenessText;
    private javax.swing.JPanel propertiesPanel;
    private javax.swing.JLabel reversibilityLabel;
    private javax.swing.JLabel reversibilityText;
    private javax.swing.JLabel safenessLabel;
    private javax.swing.JLabel safenessText;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
