/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.petri.nets.gui;

import java.awt.Color;
import java.util.Collections;
import java.util.HashMap;
import java.util.TreeMap;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author LordMajer
 */
public class LivenessPanel extends javax.swing.JPanel {

    /**
     * Creates new form LivenessPanel
     */
    public LivenessPanel(TreeMap<String,String> livenessMap) {
        initComponents();
        
        /*for(int i=0; i < 100; i++){
            JLabel label = new JLabel();
            label.setText("T" + i);
            if(i%2 == 0){
                label.setBackground(Color.red);
            }else{
                label.setBackground(Color.green);
            }
            innerPanel.add(label);
        }*/
        for(String name : livenessMap.keySet()){
            String info = livenessMap.get(name);
            JLabel label = new JLabel(name + ": " + info);
            label.setBorder(BorderFactory.createRaisedBevelBorder());
            innerPanel.add(label);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        innerPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        innerPanel.setLayout(new javax.swing.BoxLayout(innerPanel, javax.swing.BoxLayout.Y_AXIS));
        scroll.setViewportView(innerPanel);

        add(scroll, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel innerPanel;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
